version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: 1234
      POSTGRES_DB: blogitout
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: blogitoutbackendimagetwo 
    depends_on:
      - db
    ports:
      - "5001:5001"